### ISSUE TITLE
Asset references inside templates and dev server

### ISSUE THREAD

**Issue by BassOfBass** [Spence-S/simple-pug-loader#5] opened 2021-04-20 07:27 UTC
I've encountered a bizarre issue in my project where assets would randomly 404'd during development and recently would do that right after switching a page upon server start. It took quite a while for me to notice but those assets were all referenced exclusively from templates. For the test I've imported an asset directly into the entry file and it persisted throughout just fine. I also did a test run with `writeToDisk` option on and all the files were present too. So it's something about interaction between pug templates and dev server which makes it drop referenced assets on recompile I presume.

**Comment by spence-s** [comment] 2021-04-20 16:02
@BassOfBass I took a look at this on your landing-page project and was able to quickly reproduce by: 
1) `npm run dev` and go to any page that loads images
2) make any change to main.js 
3) refresh page

All the images disappear. This is not a problem with any of your loaders. This is a bug with `webpack-dev-server` or `dev-middleware` or maybe even `memory-fs`. I could repro in this way with both `pug-loader` and `simple-pug-loader`. The reason is that `webpack-dev-server` drops all your images from memory when the recompile happens for some reason. Not sure why. 

Setting `writeToDisk` to true solves this because it hold the images on disk in the correct location instead of dropping them.

I would use this as a work around for now ☝🏻 

I'm closing this because its not an issue with `simple-pug-loader`. But I encourage you to open an issue with these instructions and perhaps and updated `landing-page` repo for `webpack-dev-server`. 

Adding a couple of images here for your reference. 

1) immediately after initial build webpack-dev-server has all images in memory:
![Screen Shot 2021-04-20 at 11 55 27 AM](https://user-images.githubusercontent.com/16724951/115427315-5ddd0480-a1cf-11eb-812e-90a7efd496ba.png)

2) After making any update to the main.js 
![Screen Shot 2021-04-20 at 11 56 41 AM](https://user-images.githubusercontent.com/16724951/115427527-895fef00-a1cf-11eb-91db-b26f800743fa.png)

**Closed as completed by spence-s** 2021-04-20 16:02 UTC

**Comment by BassOfBass** [comment] 2021-04-20 17:43
Well the actual workaround is to also `require()` assets in some script, which is a part of any of the entry points. But I'll do a repro and submit an issue to `dev server` repo for sure.
